/* Sunlit Storybook: the card garden is data-driven; each word owns its image, crop position, alt text, and audio slot. */
import { useMemo, useState } from "react";
import { Volume2, Search, Sparkles, ChevronRight, BookOpen, Heart, ArrowRight } from "lucide-react";
import words from "@/data/words.json";

type Word = (typeof words)[number];
const categoryArt: Record<string, string> = { Animals: "/manus-storage/category-animals_da0768c6.png", Food: "/manus-storage/category-food_a34bcd28.png", Transport: "/manus-storage/category-transport_9bcfe0f0.png", "Nature & Home": "/manus-storage/category-nature_fbf7c2db.png" };
const categories = [{ key: "All", label: "All words", icon: "✦", color: "marigold" }, { key: "Animals", label: "Animals", icon: "🐰", color: "leaf" }, { key: "Food", label: "Food", icon: "🍎", color: "coral" }, { key: "Transport", label: "Transport", icon: "🚌", color: "sky" }, { key: "Nature & Home", label: "Nature & Home", icon: "🌼", color: "lavender" }];

function speak(word: string) { if (typeof window !== "undefined" && "speechSynthesis" in window) { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(word); utterance.lang = "en-US"; utterance.rate = 0.72; utterance.pitch = 1.12; window.speechSynthesis.speak(utterance); } }

export default function Home() {
  const [selected, setSelected] = useState("All"); const [query, setQuery] = useState(""); const [playing, setPlaying] = useState<string | null>(null);
  const filtered = useMemo(() => words.filter((item) => (selected === "All" || item.category === selected) && `${item.word} ${item.translation}`.toLowerCase().includes(query.toLowerCase())), [selected, query]);
  const featured = words[1];
  const play = (item: Word) => { setPlaying(item.id); if (item.audio) { new Audio(item.audio).play().catch(() => speak(item.word)); } else speak(item.word); window.setTimeout(() => setPlaying(null), 900); };

  return <main className="garden-shell">
    <header className="topbar"><a className="brand" href="#top" aria-label="Little Word Garden home"><span className="brand-mark"><img src="/manus-storage/little-word-garden-logo_2c085097.png" alt="" /></span><span><strong>little word</strong><em>garden</em></span></a><div className="topbar-note"><span className="sun-dot" /> Learn a little. Grow a lot.</div><button className="parent-button" onClick={() => document.getElementById("word-list")?.scrollIntoView({ behavior: "smooth" })}><BookOpen size={17} /> Explore words</button></header>
    <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15} /> A tiny English garden</div><h1>Pick a picture.<br /><span>Find a word.</span></h1><p>Friendly first words for little explorers. Tap the speaker and say it together.</p><div className="hero-actions"><button className="primary-button" onClick={() => play(featured)}>Hear a word <Volume2 size={18} /></button><span className="age-note">Made for ages 2–6 <Heart size={14} fill="currentColor" /></span></div></div><div className="hero-art"><img src={categoryArt.Animals} alt="Friendly animal illustrations" /><div className="hero-sticker sticker-one">hello!</div><div className="hero-sticker sticker-two">say it<br />with me</div></div></section>
    <section className="explore-layout" id="word-list"><aside className="category-rail"><p className="rail-label">Choose a path</p><nav aria-label="Word categories">{categories.map((category) => <button key={category.key} className={`category-button ${category.color} ${selected === category.key ? "active" : ""}`} onClick={() => setSelected(category.key)}><span className="category-icon">{category.icon}</span><span>{category.label}</span>{selected === category.key && <ChevronRight size={16} />}</button>)}</nav><div className="rail-tip"><span>✎</span><p><strong>Grown-up tip</strong><br />Point, listen, repeat. Keep it playful!</p></div></aside>
      <div className="cards-area"><div className="section-heading"><div><p className="eyebrow">Little discoveries</p><h2>{selected === "All" ? "Today’s word garden" : selected}</h2><p className="result-count">{filtered.length} friendly words to explore</p></div><label className="search-box"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Find a word" aria-label="Find a word" /></label></div>
        <div className="card-grid">{filtered.map((item, index) => <article className={`word-card card-${index % 5}`} key={item.id}><div className="card-topline"><span>{item.category}</span><span className="card-number">{String(words.indexOf(item) + 1).padStart(2, "0")}</span></div><button className={`picture-button ${playing === item.id ? "is-playing" : ""}`} onClick={() => play(item)} aria-label={`Hear ${item.word}`}>{item.image ? <img className="vocab-image" src={item.image} alt={item.imageAlt} style={{ objectPosition: item.imagePosition }} /> : <span className="emoji-picture" role="img" aria-label={item.imageAlt}>{item.emoji}</span>}<span className="sound-waves"><i /><i /><i /></span></button><div className="word-footer"><div><h3>{item.word}</h3><p>{item.translation}</p></div><button className="sound-button" onClick={() => play(item)} aria-label={`Play ${item.word}`}><Volume2 size={19} /></button></div></article>)}</div>
        {filtered.length === 0 && <div className="empty-state">Try another little word.</div>}<div className="bottom-note"><span>✿</span> Every word is a tiny seed. <button onClick={() => { setSelected("All"); setQuery(""); }}>See all words <ArrowRight size={15} /></button></div>
      </div></section><footer><span>Little Word Garden</span><span>Made for curious little voices · {words.length} words to begin</span></footer>
  </main>;
}
