import fs from "node:fs";

const file = new URL("../client/src/data/words.json", import.meta.url);
const words = JSON.parse(fs.readFileSync(file, "utf8"));
const additions = [
  ["animals-bear", "bear", "熊", "🐻", "Animals", "A cuddly brown bear"],
  ["animals-cow", "cow", "乳牛", "🐮", "Animals", "A friendly black and white cow"],
  ["animals-pig", "pig", "豬", "🐷", "Animals", "A happy pink pig"],
  ["animals-horse", "horse", "馬", "🐴", "Animals", "A gentle brown horse"],
  ["animals-sheep", "sheep", "綿羊", "🐑", "Animals", "A fluffy white sheep"],
  ["animals-goat", "goat", "山羊", "🐐", "Animals", "A little mountain goat"],
  ["animals-duck", "duck", "鴨子", "🦆", "Animals", "A cheerful yellow duck"],
  ["animals-chicken", "chicken", "雞", "🐔", "Animals", "A bright farm chicken"],
  ["animals-penguin", "penguin", "企鵝", "🐧", "Animals", "A cute little penguin"],
  ["animals-zebra", "zebra", "斑馬", "🦓", "Animals", "A stripey zebra"],
  ["food-pizza", "pizza", "披薩", "🍕", "Food", "A cheesy pizza slice"],
  ["food-pasta", "pasta", "義大利麵", "🍝", "Food", "A bowl of pasta"],
  ["food-egg", "egg", "雞蛋", "🥚", "Food", "A fresh white egg"],
  ["food-toast", "toast", "吐司", "🍞", "Food", "A warm piece of toast"],
  ["food-sandwich", "sandwich", "三明治", "🥪", "Food", "A tasty little sandwich"],
  ["food-noodles", "noodles", "麵條", "🍜", "Food", "A bowl of noodles"],
  ["food-salad", "salad", "沙拉", "🥗", "Food", "A colorful fresh salad"],
  ["food-potato", "potato", "馬鈴薯", "🥔", "Food", "A round brown potato"],
  ["food-corn", "corn", "玉米", "🌽", "Food", "A sunny yellow corn"],
  ["food-popcorn", "popcorn", "爆米花", "🍿", "Food", "A fluffy bowl of popcorn"],
  ["fruit-pear", "pear", "梨子", "🍐", "Fruit", "A sweet green pear"],
  ["fruit-lemon", "lemon", "檸檬", "🍋", "Fruit", "A bright yellow lemon"],
  ["fruit-lime", "lime", "萊姆", "🍈", "Fruit", "A little green lime"],
  ["fruit-dragon-fruit", "dragon fruit", "火龍果", "🐉", "Fruit", "A bright pink dragon fruit"],
  ["fruit-papaya", "papaya", "木瓜", "🧡", "Fruit", "A soft orange papaya"],
  ["fruit-coconut", "coconut", "椰子", "🥥", "Fruit", "A round brown coconut"],
  ["fruit-melon", "melon", "甜瓜", "🍈", "Fruit", "A sweet green melon"],
  ["fruit-raspberry", "raspberry", "覆盆子", "🍓", "Fruit", "A tiny red raspberry"],
  ["fruit-blueberry", "blueberry", "藍莓", "🫐", "Fruit", "A little blue blueberry"],
  ["fruit-avocado", "avocado", "酪梨", "🥑", "Fruit", "A green avocado"],
  ["transport-van", "van", "廂型車", "🚐", "Transport", "A friendly family van"],
  ["transport-ship", "ship", "船", "🚢", "Transport", "A big ship on the sea"],
  ["transport-ferry", "ferry", "渡輪", "⛴️", "Transport", "A ferry crossing the water"],
  ["transport-tram", "tram", "電車", "🚋", "Transport", "A bright city tram"],
  ["transport-motorcycle", "motorcycle", "摩托車", "🏍️", "Transport", "A speedy motorcycle"],
  ["transport-skateboard", "skateboard", "滑板", "🛹", "Transport", "A colorful skateboard"],
  ["transport-ambulance", "ambulance", "救護車", "🚑", "Transport", "A helpful ambulance"],
  ["transport-police-car", "police car", "警車", "🚓", "Transport", "A helpful police car"],
  ["transport-sailboat", "sailboat", "帆船", "⛵", "Transport", "A little sailboat"],
  ["transport-hot-air-balloon", "hot air balloon", "熱氣球", "🎈", "Transport", "A colorful hot air balloon"],
  ["nature-river", "river", "河流", "🏞️", "Nature & Home", "A winding blue river"],
  ["nature-mountain", "mountain", "山", "⛰️", "Nature & Home", "A tall green mountain"],
  ["nature-sea", "sea", "海", "🌊", "Nature & Home", "A sparkling blue sea"],
  ["nature-leaf", "leaf", "葉子", "🍃", "Nature & Home", "A fresh green leaf"],
  ["nature-seed", "seed", "種子", "🌱", "Nature & Home", "A tiny growing seed"],
  ["nature-garden", "garden", "花園", "🌷", "Nature & Home", "A sunny little garden"],
  ["nature-door", "door", "門", "🚪", "Nature & Home", "A bright blue door"],
  ["nature-window", "window", "窗戶", "🪟", "Nature & Home", "A sunny window"],
  ["nature-table", "table", "桌子", "🪑", "Nature & Home", "A little wooden table"],
  ["nature-lamp", "lamp", "檯燈", "💡", "Nature & Home", "A warm little lamp"],
  ["colors-black", "black", "黑色", "⚫", "Colors", "A deep black color"],
  ["colors-white", "white", "白色", "⚪", "Colors", "A clean white color"],
  ["colors-brown", "brown", "棕色", "🟤", "Colors", "A warm brown color"],
  ["colors-gray", "gray", "灰色", "🩶", "Colors", "A soft gray color"],
  ["colors-gold", "gold", "金色", "🥇", "Colors", "A shiny gold color"],
  ["colors-silver", "silver", "銀色", "🪙", "Colors", "A bright silver color"],
  ["colors-teal", "teal", "藍綠色", "🔷", "Colors", "A calm teal color"],
  ["colors-beige", "beige", "米色", "🟫", "Colors", "A gentle beige color"],
  ["colors-navy", "navy", "深藍色", "🔵", "Colors", "A deep navy color"],
  ["colors-coral", "coral", "珊瑚色", "🪸", "Colors", "A warm coral color"],
  ["numbers-zero", "zero", "零", "0️⃣", "Numbers", "The number zero"],
  ["numbers-eight", "eight", "八", "8️⃣", "Numbers", "The number eight"],
  ["numbers-nine", "nine", "九", "9️⃣", "Numbers", "The number nine"],
  ["numbers-ten", "ten", "十", "🔟", "Numbers", "The number ten"],
  ["numbers-eleven", "eleven", "十一", "🔢", "Numbers", "The number eleven"],
  ["numbers-twelve", "twelve", "十二", "🔢", "Numbers", "The number twelve"],
  ["numbers-thirteen", "thirteen", "十三", "🔢", "Numbers", "The number thirteen"],
  ["numbers-fourteen", "fourteen", "十四", "🔢", "Numbers", "The number fourteen"],
  ["numbers-fifteen", "fifteen", "十五", "🔢", "Numbers", "The number fifteen"],
  ["numbers-sixteen", "sixteen", "十六", "🔢", "Numbers", "The number sixteen"],
  ["shapes-rectangle", "rectangle", "長方形", "▭", "Shapes", "A blue rectangle"],
  ["shapes-diamond", "diamond", "菱形", "🔶", "Shapes", "An orange diamond"],
  ["shapes-cube", "cube", "立方體", "🧊", "Shapes", "A little blue cube"],
  ["shapes-cone", "cone", "圓錐形", "🍦", "Shapes", "A tall ice cream cone"],
  ["shapes-crescent", "crescent", "新月形", "🌙", "Shapes", "A gentle crescent shape"],
  ["shapes-hexagon", "hexagon", "六角形", "⬡", "Shapes", "A green hexagon"],
  ["shapes-octagon", "octagon", "八角形", "🛑", "Shapes", "A red octagon"],
  ["shapes-line", "line", "線", "➖", "Shapes", "A straight line"],
  ["shapes-semicircle", "semicircle", "半圓形", "◐", "Shapes", "A happy semicircle"],
  ["shapes-cross", "cross", "十字形", "✚", "Shapes", "A simple cross shape"],
  ["body-head", "head", "頭", "🙂", "Body Parts", "A smiling little head"],
  ["body-hair", "hair", "頭髮", "💇", "Body Parts", "Soft brown hair"],
  ["body-mouth", "mouth", "嘴巴", "👄", "Body Parts", "A smiling mouth"],
  ["body-teeth", "teeth", "牙齒", "🦷", "Body Parts", "Clean little teeth"],
  ["body-tongue", "tongue", "舌頭", "😛", "Body Parts", "A playful tongue"],
  ["body-arm", "arm", "手臂", "💪", "Body Parts", "A strong little arm"],
  ["body-leg", "leg", "腿", "🦵", "Body Parts", "A running leg"],
  ["body-knee", "knee", "膝蓋", "🦵", "Body Parts", "A little knee"],
  ["body-toes", "toes", "腳趾", "🦶", "Body Parts", "Tiny toes"],
  ["body-tummy", "tummy", "肚子", "🤰", "Body Parts", "A cozy tummy"],
  ["clothes-dress", "dress", "洋裝", "👗", "Clothes", "A pretty red dress"],
  ["clothes-skirt", "skirt", "裙子", "👚", "Clothes", "A twirly skirt"],
  ["clothes-coat", "coat", "外套", "🧥", "Clothes", "A warm winter coat"],
  ["clothes-jacket", "jacket", "夾克", "🥼", "Clothes", "A bright jacket"],
  ["clothes-boots", "boots", "靴子", "👢", "Clothes", "A pair of rain boots"],
  ["clothes-gloves", "gloves", "手套", "🧤", "Clothes", "Warm little gloves"],
  ["clothes-scarf", "scarf", "圍巾", "🧣", "Clothes", "A cozy red scarf"],
  ["clothes-belt", "belt", "皮帶", "🧷", "Clothes", "A brown belt"],
  ["clothes-pajamas", "pajamas", "睡衣", "🛌", "Clothes", "Soft bedtime pajamas"],
  ["clothes-crown", "crown", "皇冠", "👑", "Clothes", "A shiny golden crown"]
].map(([id, word, translation, emoji, category, imageAlt]) => ({
  id, word, translation, emoji, category, image: null, imagePosition: "50% 50%", imageAlt,
  englishAudio: null, chineseAudio: null, speech: { englishLocale: "en-US", chineseLocale: "zh-TW" }
}));

const existingIds = new Set(words.map((word) => word.id));
const existingWords = new Set(words.map((word) => word.word.toLowerCase()));
const uniqueAdditions = additions.filter((word) => !existingIds.has(word.id) && !existingWords.has(word.word.toLowerCase()));
if (uniqueAdditions.length !== 100 || words.length + uniqueAdditions.length !== 200) {
  throw new Error(`Expected 100 unique additions and 200 total words, got ${uniqueAdditions.length} additions and ${words.length + uniqueAdditions.length} total.`);
}
fs.writeFileSync(file, `${JSON.stringify([...words, ...uniqueAdditions], null, 2)}\n`);
console.log(`Added ${uniqueAdditions.length} unique words; total is ${words.length + uniqueAdditions.length}.`);
